import { z } from "zod";

export const productSchema = z.object({
  id: z.string().optional(),
  name: z.string().min(2),
  sku: z.string().min(2),
  price: z.coerce.number().positive(),
  promoPrice: z.coerce.number().positive().nullable().optional(),
  shortDescription: z.string().min(2),
  description: z.string().min(2),
  benefitsAndUsage: z.string().nullable().optional(),
  seoTitle: z.string().nullable().optional(),
  seoDescription: z.string().nullable().optional(),
  keywords: z.string().nullable().optional(),
  variantsJson: z.string().nullable().optional(),
  shippingJson: z.string().nullable().optional(),
  protectionJson: z.string().nullable().optional(),
  marketplaceJson: z.string().nullable().optional(),
  specsJson: z.string().nullable().optional(),
  discountJson: z.string().nullable().optional(),
  categoryId: z.string().min(1),
  stock: z.coerce.number().int().min(0),
  status: z.enum(["active", "draft", "hidden"]),
  brand: z.string().min(1),
  condition: z.string().min(1),
  color: z.string().nullable().optional(),
  size: z.string().nullable().optional(),
  model: z.string().nullable().optional(),
  images: z.array(z.object({
    url: z.string().url(),
    publicId: z.string().nullable().optional(),
    mediaType: z.enum(["image", "video"]).optional(),
  })).default([]),
});

export const discountSchema = z.object({
  id: z.string().optional(),
  name: z.string().min(2),
  type: z.enum(["product", "category", "global", "new_customer", "limited_time", "flash_sale", "promo_code"]),
  enabled: z.coerce.boolean(),
  percent: z.coerce.number().min(0).max(95).nullable().optional(),
  badge: z.string().nullable().optional(),
  code: z.string().nullable().optional(),
  startDate: z.string().nullable().optional(),
  endDate: z.string().nullable().optional(),
  newCustomerDays: z.coerce.number().int().min(0).nullable().optional(),
  minAmount: z.coerce.number().min(0).nullable().optional(),
  categoriesJson: z.string().nullable().optional(),
  excludedProductsJson: z.string().nullable().optional(),
});

export const bannerSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(2),
  subtitle: z.string().min(2),
  imageUrl: z.string().url().or(z.literal("")),
  publicId: z.string().nullable().optional(),
  productImageUrl: z.string().url().nullable().optional().or(z.literal("")),
  productPublicId: z.string().nullable().optional(),
  productImages: z.array(z.object({
    url: z.string().url(),
    publicId: z.string().nullable().optional(),
  })).optional(),
  ctaText: z.string().min(1),
  ctaLink: z.string().min(1),
  position: z.enum(["homepage_hero", "category_banner", "promo_banner"]),
  backgroundColor: z.string().min(1).optional(),
  gradient: z.string().nullable().optional(),
  imagePosition: z.enum(["left", "right", "center", "top", "bottom"]).optional(),
  textPosition: z.enum(["left", "right", "center"]).optional(),
  size: z.enum(["large", "medium", "small"]).optional(),
  titleSize: z.enum(["small", "medium", "large", "xlarge"]).optional(),
  textColor: z.string().min(1).optional(),
  subtitleColor: z.string().min(1).optional(),
  fontFamily: z.enum(["sans", "serif", "display", "mono"]).optional(),
  textBadgeEnabled: z.coerce.boolean().optional(),
  textBadgeColor: z.string().min(1).optional(),
  textBadgeTextColor: z.string().min(1).optional(),
  active: z.coerce.boolean(),
});

export const announcementSchema = z.object({
  id: z.string().optional(),
  text: z.string().min(2),
  link: z.string().nullable().optional(),
  imageUrl: z.string().url().nullable().optional().or(z.literal("")),
  publicId: z.string().nullable().optional(),
  type: z.enum(["top_bar", "popup", "product_promo", "homepage_section"]),
  startDate: z.string().min(1),
  endDate: z.string().min(1),
  active: z.coerce.boolean(),
});

export const sellerSchema = z.object({
  id: z.string().optional(),
  storeName: z.string().min(2),
  contactName: z.string().min(2),
  email: z.string().email(),
  password: z.string().min(8).optional().or(z.literal("")),
  phone: z.string().nullable().optional(),
  logoUrl: z.string().url().nullable().optional().or(z.literal("")),
  coverUrl: z.string().url().nullable().optional().or(z.literal("")),
  description: z.string().nullable().optional(),
  returnPolicy: z.string().nullable().optional(),
  shippingDelay: z.string().nullable().optional(),
  commissionRate: z.coerce.number().min(0).max(80).nullable().optional(),
  status: z.enum(["pending", "active", "suspended", "rejected"]).optional(),
});
